name: Tear down for test
description: Makes any necessary changes to clean up after running a test
# TODO: Delete any open PRs on the site repo.

runs:
  using: composite
  steps:
    - name: Tear down for test
      shell: bash
      run: |
        # Tear down for test
        pushd local
        if git show-branch remotes/origin/config-only &> /dev/null; then
          git push -d origin config-only
        fi
        popd
        
        tmp=$(mktemp -d)
        mv test/update-config "$tmp"
        rm -rf * .* || true
        mkdir test
        mv "$tmp/update-config" test
        rm -rf "$tmp"
