name: Tear down for test
description: Makes any necessary changes to clean up after running a test

inputs:
  branch_prefix:
    description: The prefix used for test branches.
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Tear down for test
      shell: bash
      working-directory: test
      run: |
        set -eu
        # Tear down for test
        for directory in remote site; do
          pushd "$directory"
          git for-each-ref "refs/remotes/origin/${{ inputs.branch_prefix }}*" --format '%(refname:short)' | while read refname; do
            branch=${refname//'origin/'/}
            git push -d origin $branch
            echo "Deleted $directory branch '$branch'."
          done
          popd
        done
