name: Tear down for test
description: Makes any necessary changes to clean up after running a test
# TODO: Delete any open PRs on the site repo.

runs:
  using: composite
  steps:
    - name: Tear down for test
      shell: bash
      run: |
        tmp=$(mktemp -d)
        mv test/config-update "$tmp"
        rm -rf * .*
        mkdir test
        mv "$tmp/config-update" test
        rm -rf "$tmp"
