name: Tear down for test
description: Makes any necessary changes to clean up after running a test
# TODO: Delete any open PRs on the site repo.

runs:
  using: composite
  steps:
    - name: Tear down for test
      shell: bash
      run: |
        # Tear down for test
        if git show-branch remotes/origin/config-only &> /dev/null; then
          git push -d origin config-only
        fi
#        if [[ "$(gh pr list -H automatic-config-export --json id)" !=
