name: Tear down for test
description: Makes any necessary changes to clean up after running a test

inputs:
  branch_prefix:
    description: The prefix used for test branches.
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Tear down for test
      shell: bash
      working-directory: test/site
      run: |
        # Tear down for test
        set -eu
        git for-each-ref "refs/remotes/origin/${{ inputs.branch_prefix }}*" --format '%(refname:short)' | while read refname
          do git push -d origin ${refname//'origin/'/}
        done
