name: Setup for test
description: Prepares test repos for automated testing.
# TODO: Delete any open PRs on the site repo.

inputs:
  test_site_repo:
    description: The GitHub site repo for use with the test.
    type: string
    required: true
  test_site_repo_token:
    description: A token with write access to the test site repo.
    type: string
    required: true
  test_config_repo:
    description: The GitHub config repo for use with the test.
    type: string
    required: true
  test_config_repo_token:
    description: A token with write access to the test config repo.
    type: string
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        repository: ${{ input.test_site_repo }}
        token: ${{ inputs.test_site_repo_token }}
        path: test/site
        fetch-depth: 0

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.test_config_repo }}
        token: ${{ inputs.test_config_repo_token }}
        path: test/remote
        fetch-depth: 0

    - name: Setup for test
      shell: bash
      working-directory: test
      run: |
        # Setup for test
        git config --global user.name 'Test User'
        git config --global user.email 'test@example.com'

        pushd remote
        git checkout --orphan new-main
        git rm -rf .
        touch c d e
        git add .
        git commit -m "Add initial mock config"
        echo modified > c
        git add c
        git commit -m "Updated c"
        git push origin HEAD:main --force
        git checkout main
        git reset --hard new-main
        git branch -d new-main
        popd

        pushd site
        git checkout --orphan new-staging
        git rm -rf .
        mkdir -p a z config/sync 
        touch {a,z}/.gitkeep b config/sync/{c,d,e}
        git config user.name 'Test User'
        git config user.email 'test@example.com'
        git add .
        git commit -m "Add mock Drupal site"
        git push origin HEAD:staging --force
        git checkout staging
        git reset --hard new-staging
        git branch -d new-staging
        
        git push -d origin config-only || true

        git push origin HEAD --force
        popd
