name: Common test assertions
description: Provides common test assertions for all tests
# TBH this also has side-effects, could do with a different name.

inputs:
    test_config_repo:
      description: The GitHub config repo for use with the test.
      type: string
      required: true
    test_config_repo_token:
      description: A token with write access to the test config repo.
      type: string
      required: true
    test_config_repo_branch:
      description: The main branch on the config repository.
      type: string
      required: true
    test_site_repo_config_branch:
      description: The branch on the site repository that mirrors the config repository.
      type: string
      required: true
    test_site_repo:
      description: The GitHub site repo for use with the test.
      type: string
      required: true
    test_site_repo_token:
      description: A token with write access to the test site repo.
      type: string
      required: true

runs:
  using: composite
  steps:
    - uses: ./test/update-config/.github/actions/test-checkout
      with:
        test_config_repo: ${{ inputs.test_config_repo }}
        test_config_repo_token: ${{ inputs.test_config_repo_token }}
        test_site_repo: ${{ inputs.test_site_repo }}
        test_site_repo_token: ${{ inputs.test_site_repo_token }}

    - name: Assert the state after running the action
      shell: sh
      working-directory: test
      run: |
        # Assert the state after running the action
        set -eu

        if [[ "$(git -C remote rev-parse origin/${{ inputs.test_config_repo_branch }})" != "$(git -C site rev-parse origin/${{ inputs.test_site_repo_config_branch }})" ]]; then
          echo "**TEST FAILURE:** The Drupal site repo's config-only branch wasn't in sync with the config repo's main branch." >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
