name: Check for config updates

# Calls the update-config action.
#
# Note that GitHub's scheduled tasks aren't guaranteed to run when they're
# scheduled; if you want that guarantee they should be triggered externally.
#
# Workflow permissions: The repo must be configured to support GitHub actions
# making PRs.
# Secrets:
# - CONFIG_REPO_TOKEN: The config repo token with content read access.
# Variables:
# - CONFIG_REPO: The GitHub config repo, eg. BrooksDigital/AbcConfig.
# - SITE_REPO_PR_BRANCH_BASE: (optional) The branch from which the config topic
#   branch will be made for the PR; defaults to 'staging'.
# - GITHUB_NOTIFY: (optional) A space-separated list of github users including
#   '@' to ping on a new PR, eg. '@andy @becca'.

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/30 * * * *'

concurrency:
  group: update-config-branch

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: andriokha/auto-config-export@main
        with:
          config_repo: ${{ vars.CONFIG_REPO }}
          config_repo_token: ${{ secrets.CONFIG_REPO_TOKEN }}
          github_notify: ${{ vars.GITHUB_NOTIFY }}
          site_repo_pr_branch_base: ${{ vars.SITE_REPO_PR_BRANCH_BASE || 'staging' }}
