name: Test
# THIS IS FOR TESTING THE ACTION: DO NOT USE IT IN YOUR DRUPAL PROJECT, USE
# workflow-templates/update-config-branch.yml instead.
#
# Secrets
# - TEST_CONFIG_REPO_TOKEN: A token with write access to the test config repo.
# - TEST_SITE_REPO_TOKEN: A token with write access to the test site repo.
# Variables
# - TEST_CONFIG_REPO: The GitHub config repo for use with the test.
# - TEST_SITE_REPO: The GitHub repo for use with the test.

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.TEST_SITE_REPO }}
          token: ${{ secrets.TEST_SITE_REPO_TOKEN }}
          path: test/site
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          repository: ${{ vars.TEST_CONFIG_REPO }}
          token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
          path: test/remote
          fetch-depth: 0

      - uses: ./.github/actions/test-setup

      - uses: andriokha/auto-config-export@main
        with:
          config_repo: ${{ vars.TEST_CONFIG_REPO }}
          config_repo_token: ${{ secrets.TEST_CONFIG_REPO_TOKEN }}
          site_repo: ${{ vars.TEST_SITE_REPO }}
          site_repo_token: ${{ secrets.TEST_SITE_REPO_TOKEN }}

      - name: Assert the state after running the action
        env:
          GH_TOKEN: ${{ secrets.TEST_SITE_REPO_TOKEN }}
        run: |
          set -eux
          cd test/site
          git fetch
          git checkout staging
          if [[ "$(gh pr list --json id)" != "[]" ]]; then
            exit 1
          fi
        

        # TEARDOWN DELETE NAY PRS
